## First import pandas, numpy and requests.

## Next I set the link to the wikipedia page as wiki_url to pass it to the panda.read_html function.

In [2]:
import pandas as pd
import requests
import numpy as np
wiki_url='https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'

## Next I used df[0] to turn it into a dataframe

In [3]:
df=pd.read_html(wiki_url)
df=df[0]
df.head()

  Postal Code           Borough              Neighbourhood
0         M1A      Not assigned               Not assigned
1         M2A      Not assigned               Not assigned
2         M3A        North York                  Parkwoods
3         M4A        North York           Victoria Village
4         M5A  Downtown Toronto  Regent Park, Harbourfront

## I changed the "Not assigned" cells to the numpy NaN placeholder so I could use the panda.dropna method.

## The index no longer started at zero so I reset the index and dropped the old one.

In [6]:
df.replace("Not assigned", np.nan, inplace = True)
df.dropna(axis = 0, inplace=True)
df.reset_index(drop=True,inplace=True)
df.head()

  Postal Code           Borough                                Neighbourhood
0         M3A        North York                                    Parkwoods
1         M4A        North York                             Victoria Village
2         M5A  Downtown Toronto                    Regent Park, Harbourfront
3         M6A        North York             Lawrence Manor, Lawrence Heights
4         M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government

In [7]:
df.shape

(103, 3)

### The result has three columns and 103 rows.